/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Edwin
 */
public class FrmPersonalChofer extends javax.swing.JFrame {

    /**
     * Creates new form FrmPersonalChofer
     */
    public FrmPersonalChofer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigoLicencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ChecCodigoLicencia = new javax.swing.JCheckBox();
        ChecCodigoSCTR = new javax.swing.JCheckBox();
        txtCodigoSCTR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbLicenciaAIV = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ChecLicenciaAIV = new javax.swing.JCheckBox();
        cmbSexo2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ChecSexo2 = new javax.swing.JCheckBox();
        cmbPlanilla = new javax.swing.JComboBox<>();
        ChecPlantilla = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtCargarArchivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ChecCargarArchivo = new javax.swing.JCheckBox();
        btnSeleccionarArchivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnContinuar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtCodigoLicencia.setBackground(new java.awt.Color(218, 218, 218));
        txtCodigoLicencia.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCodigoLicencia.setBorder(null);
        jPanel1.add(txtCodigoLicencia);
        txtCodigoLicencia.setBounds(20, 40, 170, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("CODIGO LICENCIA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 110, 20);

        ChecCodigoLicencia.setBackground(new java.awt.Color(255, 255, 255));
        ChecCodigoLicencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChecCodigoLicencia.setForeground(new java.awt.Color(210, 126, 0));
        ChecCodigoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecCodigoLicenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ChecCodigoLicencia);
        ChecCodigoLicencia.setBounds(190, 40, 20, 21);

        ChecCodigoSCTR.setBackground(new java.awt.Color(255, 255, 255));
        ChecCodigoSCTR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChecCodigoSCTR.setForeground(new java.awt.Color(210, 126, 0));
        ChecCodigoSCTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecCodigoSCTRActionPerformed(evt);
            }
        });
        jPanel1.add(ChecCodigoSCTR);
        ChecCodigoSCTR.setBounds(420, 40, 20, 21);

        txtCodigoSCTR.setBackground(new java.awt.Color(218, 218, 218));
        txtCodigoSCTR.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCodigoSCTR.setBorder(null);
        jPanel1.add(txtCodigoSCTR);
        txtCodigoSCTR.setBounds(250, 40, 170, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("CODIGO SCTR:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 20, 90, 20);

        cmbLicenciaAIV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si (Activo)", "Si (Inactivo)", "No" }));
        cmbLicenciaAIV.setBorder(null);
        jPanel1.add(cmbLicenciaAIV);
        cmbLicenciaAIV.setBounds(20, 160, 170, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("LICENCIA A-IV:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 140, 100, 20);

        ChecLicenciaAIV.setBackground(new java.awt.Color(255, 255, 255));
        ChecLicenciaAIV.setForeground(new java.awt.Color(210, 126, 0));
        ChecLicenciaAIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecLicenciaAIVActionPerformed(evt);
            }
        });
        jPanel1.add(ChecLicenciaAIV);
        ChecLicenciaAIV.setBounds(190, 160, 20, 21);

        cmbSexo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "A-I", "A-IIa", "A-IIb", "A-IIIa", "A-IIIb", "A-IIIc", " ", " " }));
        cmbSexo2.setBorder(null);
        jPanel1.add(cmbSexo2);
        cmbSexo2.setBounds(20, 100, 170, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("TIPO LICENCIA:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 80, 90, 20);

        ChecSexo2.setBackground(new java.awt.Color(255, 255, 255));
        ChecSexo2.setForeground(new java.awt.Color(210, 126, 0));
        ChecSexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecSexo2ActionPerformed(evt);
            }
        });
        jPanel1.add(ChecSexo2);
        ChecSexo2.setBounds(190, 100, 20, 21);

        cmbPlanilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));
        cmbPlanilla.setBorder(null);
        jPanel1.add(cmbPlanilla);
        cmbPlanilla.setBounds(250, 100, 170, 20);

        ChecPlantilla.setBackground(new java.awt.Color(255, 255, 255));
        ChecPlantilla.setForeground(new java.awt.Color(210, 126, 0));
        ChecPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecPlantillaActionPerformed(evt);
            }
        });
        jPanel1.add(ChecPlantilla);
        ChecPlantilla.setBounds(420, 100, 20, 21);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("PLANILLA:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(250, 80, 70, 20);

        txtCargarArchivo.setBackground(new java.awt.Color(218, 218, 218));
        txtCargarArchivo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtCargarArchivo.setBorder(null);
        jPanel1.add(txtCargarArchivo);
        txtCargarArchivo.setBounds(350, 160, 70, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CARGAR ARCHIVO:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 140, 120, 20);

        ChecCargarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        ChecCargarArchivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChecCargarArchivo.setForeground(new java.awt.Color(210, 126, 0));
        ChecCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecCargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(ChecCargarArchivo);
        ChecCargarArchivo.setBounds(420, 160, 20, 21);

        btnSeleccionarArchivo.setBackground(new java.awt.Color(210, 126, 0));
        btnSeleccionarArchivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSeleccionarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarArchivo.setText("ARCHIVO");
        jPanel1.add(btnSeleccionarArchivo);
        btnSeleccionarArchivo.setBounds(250, 160, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 200);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnContinuar1.setBackground(new java.awt.Color(210, 126, 0));
        btnContinuar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnContinuar1.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar1.setText("REGISTRAR");
        jPanel2.add(btnContinuar1);
        btnContinuar1.setBounds(30, 80, 100, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 0, 160, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChecCodigoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecCodigoLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecCodigoLicenciaActionPerformed

    private void ChecCodigoSCTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecCodigoSCTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecCodigoSCTRActionPerformed

    private void ChecLicenciaAIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecLicenciaAIVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecLicenciaAIVActionPerformed

    private void ChecSexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecSexo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecSexo2ActionPerformed

    private void ChecPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecPlantillaActionPerformed

    private void ChecCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecCargarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChecCargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonalChofer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox ChecCargarArchivo;
    public javax.swing.JCheckBox ChecCodigoLicencia;
    public javax.swing.JCheckBox ChecCodigoSCTR;
    public javax.swing.JCheckBox ChecLicenciaAIV;
    public javax.swing.JCheckBox ChecPlantilla;
    public javax.swing.JCheckBox ChecSexo2;
    public javax.swing.JButton btnContinuar1;
    public javax.swing.JButton btnSeleccionarArchivo;
    public javax.swing.JComboBox<String> cmbLicenciaAIV;
    public javax.swing.JComboBox<String> cmbPlanilla;
    public javax.swing.JComboBox<String> cmbSexo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCargarArchivo;
    public javax.swing.JTextField txtCodigoLicencia;
    public javax.swing.JTextField txtCodigoSCTR;
    // End of variables declaration//GEN-END:variables
}
